# Generated by Django 4.2.13 on 2024-05-29 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=511, primary_key=True, serialize=False, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=63, null=True, verbose_name='Phone')),
                ('rut', models.CharField(blank=True, db_index=True, max_length=31, null=True, verbose_name='RUT')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=511, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=511, null=True, verbose_name='Last name')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('picture', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Avatar')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (0, 'Unknown')], default=0, verbose_name='Gender')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Email verified at')),
                ('role', models.CharField(default='updater', max_length=31, verbose_name='Role')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserEmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=7, verbose_name='Verification code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'user_email_verifications',
            },
        ),
        migrations.CreateModel(
            name='UserAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('soft_delete', 'Soft Delete'), ('restore', 'Restore'), ('excel_export', 'Excel Export')], default='create', max_length=31, verbose_name='Type')),
                ('model_name', models.CharField(max_length=127, verbose_name='Model name')),
                ('model_id', models.CharField(max_length=127, verbose_name='Model ID')),
                ('principle_model_name', models.CharField(blank=True, max_length=127, null=True, verbose_name='Principle model name')),
                ('principle_model_id', models.CharField(blank=True, max_length=127, null=True, verbose_name='Principle model ID')),
                ('old_data', models.JSONField(blank=True, null=True, verbose_name='Old data')),
                ('new_data', models.JSONField(blank=True, null=True, verbose_name='New data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'user_audits',
            },
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.TextField()),
                ('intended_use', models.TextField()),
                ('request_model', models.CharField(max_length=255)),
                ('request_detail', models.JSONField(blank=True, null=True)),
                ('file_link', models.CharField(blank=True, max_length=1023, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=31)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_requests',
            },
        ),
    ]
